version: '3'
services:
  composer:
    user: "${USER_ID}:${GROUP_ID}"
    image: composer:2.5
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: no
  php:
    user: "${USER_ID}:${GROUP_ID}"
    image: php:8.2-cli
    restart: no
    volumes:
      - .:/app
    working_dir: /app